---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetrisgame
  template:
    metadata:
      labels:
        app: tetrisgame
    spec:
      containers:
        - name: cont-1
          image: harikan65/mytetrisgame:v2
          ports:
            - containerPort: 3000


